import { http } from './http';
export const api = {
    register: (payload) => http.post('/auth/register', payload),
    login: (payload) => http.post('/auth/login', payload),
    adminLogin: (payload) => http.post('/admin/auth/login', payload),
    problems: (params) => http.get('/problems', { params }),
    problemDetail: (id) => http.get(`/problems/${id}`),
    createSubmission: (payload) => http.post('/submissions', payload),
    runTest: (payload) => http.post('/submissions/run-test', payload),
    submissions: (params) => http.get('/submissions', { params }),
    submissionDetail: (id) => http.get(`/submissions/${id}`),
    explain: (id) => http.get(`/submissions/${id}/ai-explain`),
    wrongQuestions: (params) => http.get('/wrong-questions', { params }),
    recommendations: (params) => http.get('/recommendations', { params }),
    recommendRecords: (params) => http.get('/recommendations/records', { params }),
    stats: () => http.get('/users/me/stats'),
    weakPoints: (params) => http.get('/users/me/weak-points', { params }),
    learningAdvice: () => http.get('/users/me/learning-advice'),
    profile: () => http.get('/users/me/profile'),
    updateProfile: (payload) => http.put('/users/me/profile', payload),
    updatePassword: (payload) => http.put('/users/me/password', payload),
    adminUsers: (params) => http.get('/admin/users', { params }),
    adminUpdateUserStatus: (id, status) => http.put(`/admin/users/${id}/status`, { status }),
    adminProblems: (params) => http.get('/admin/problems', { params }),
    adminTags: (params) => http.get('/admin/tags', { params }),
    adminCreateTag: (payload) => http.post('/admin/tags', payload),
    adminDeleteTag: (id, force = false) => http.delete(`/admin/tags/${id}?force=${force}`),
    adminResources: (params) => http.get('/admin/resources', { params }),
    adminMonitorOverview: () => http.get('/admin/monitor/overview')
};
